meta_product_name: "ONTRACK"

meta_title: "ONTRACK – Find the music you love."

meta_description: "Get your vibe! Search for your favorite song. Discover the music you like. Based on your mood - ONTRACK made a vibe."

meta_image: "cover.png" # should exist in `app/assets/images/`
